In [1]:
import numpy as np
import pandas as pd

# загружаем созданные датасеты
has_nan = np.load('fin_has_nan.npy')
no_nan = np.load('fin_no_nan.npy')
has_nan.shape, no_nan.shape

((160, 8, 2), (160, 8, 2))

In [2]:
data = np.load('ihb_1.npy') # изменили название, потому что оно такое же как для 2 задачи
data.shape

(320, 10, 246)

In [3]:
mask = [np.isnan(data[i]).any() for i in range(data.shape[0])]
has_nan_p = np.arange(160)
no_nan_p = np.arange(160)

In [4]:
for i in range(len(has_nan)):
    has_nan_p[int(has_nan[i, 0, -1])] = has_nan_p[i] # обьединяем в пары самые скорелированные
        
has_nan_p

array([  0,   1,   0,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  18,  25,  30,  31,  32,  33,   9,  35,  36,  37,  38,
        39,  26,  41,  39,  43,  12,  45,  46,  47,  48,  49,  50,  51,
         5,  24,  54,  55,  56,  57,  19,  11,  60,  61,  62,  63,  64,
        65,  66,   7,  68,  69,  70,  70,  72,  73,  72,  13,  46,  21,
         1,   3,   6,  20,  10,  83,  84,  37,  86,  86,  88,  89,  68,
        35,  22,  93,  14,  31,  17,  27,  15,  99,  38, 101, 102,  66,
        48,  51, 106,   4, 108,  84, 110, 111,  63, 113, 108, 115,  16,
       117,  36, 101,  55,  30,  49,  61, 115, 125,  60,  57,  88, 102,
       110, 131, 111,  89,   8,  93,  69,  99,  54,  23,  41,  32, 142,
        45, 117,  43,  56,  33, 113,  50, 106, 142,  83,  62,  73,  65,
       131,  47, 125,  64])

In [5]:
c = 0
# приводим к значениям из [0, 80)
for i in range(160):
    if i in has_nan_p:
        has_nan_p[has_nan_p == i] = c
        c += 1
has_nan_p, max(has_nan_p)

(array([ 0,  1,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 17, 24, 27, 28, 29, 30,
         8, 31, 32, 33, 34, 35, 25, 36, 35, 37, 11, 38, 39, 40, 41, 42, 43,
        44,  4, 23, 45, 46, 47, 48, 18, 10, 49, 50, 51, 52, 53, 54, 55,  6,
        56, 57, 58, 58, 59, 60, 59, 12, 39, 20,  1,  2,  5, 19,  9, 61, 62,
        33, 63, 63, 64, 65, 56, 31, 21, 66, 13, 28, 16, 26, 14, 67, 34, 68,
        69, 55, 41, 44, 70,  3, 71, 62, 72, 73, 52, 74, 71, 75, 15, 76, 32,
        68, 46, 27, 42, 50, 75, 77, 49, 48, 64, 69, 72, 78, 73, 65,  7, 66,
        57, 67, 45, 22, 36, 29, 79, 38, 76, 37, 47, 30, 74, 43, 70, 79, 61,
        51, 60, 54, 78, 40, 77, 53]),
 79)

In [6]:
# то же самое для второго датасета
for i in range(len(no_nan)):
    no_nan_p[int(no_nan[i, 0, -1])] = no_nan_p[i]
no_nan_p += 80
no_nan_p

array([ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  89,  95,  96,  97,  98,  99, 100, 101, 102,  99, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 100, 115, 116, 117,  97,
       119, 120, 121, 122, 115, 124, 112, 107, 108, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 117, 138, 139, 140, 109, 142, 143, 144,
        88, 136,  85, 122, 149, 116, 124, 152, 153, 154, 155, 156, 120,
       158, 138, 160, 155, 162, 163, 134,  96, 166, 167,  93,  84, 170,
        87, 172, 173, 113, 106, 176,  83, 167, 156, 160, 158, 182, 144,
        86, 185, 140, 129, 102, 135, 132, 191, 192, 166, 128, 162, 185,
        91, 163, 172, 200, 192, 105,  80, 143, 153, 182, 207, 111, 149,
       210, 207, 133, 213,  92, 139, 154, 119, 176, 142, 110, 210,  98,
        82,  90, 173, 131, 101, 200,  95, 230,  81, 104, 191, 130, 230,
       170, 152, 213, 121])

In [7]:
c = 80
for i in range(80, 80+160):
    if i in no_nan_p:
        no_nan_p[no_nan_p == i] = c
        c += 1
no_nan_p, max(no_nan_p)

(array([ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  89,  94,  95,  96,  97,  98,  99, 100, 101,  98, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111,  99, 112, 113, 114,  96,
        115, 116, 117, 118, 112, 119, 110, 105, 106, 120, 121, 122, 123,
        124, 125, 126, 127, 128, 114, 129, 130, 131, 107, 132, 133, 134,
         88, 128,  85, 118, 135, 113, 119, 136, 137, 138, 139, 140, 116,
        141, 129, 142, 139, 143, 144, 126,  95, 145, 146,  93,  84, 147,
         87, 148, 149, 111, 104, 150,  83, 146, 140, 142, 141, 151, 134,
         86, 152, 131, 121, 101, 127, 124, 153, 154, 145, 120, 143, 152,
         91, 144, 148, 155, 154, 103,  80, 133, 137, 151, 156, 109, 135,
        157, 156, 125, 158,  92, 130, 138, 115, 150, 132, 108, 157,  97,
         82,  90, 149, 123, 100, 155,  94, 159,  81, 102, 153, 122, 159,
        147, 136, 158, 117]),
 159)

In [8]:
len(set(no_nan_p)), len(set(has_nan_p)) # смотрим, что все правильно

(80, 80)

In [9]:
# обьединяем по маске
preds = np.zeros(data.shape[0], dtype=int)
preds[mask] = has_nan_p
preds[~np.array(mask)] = no_nan_p
preds

array([ 80,   0,  81,  82,   1,   0,  83,  84,   2,   3,   4,  85,  86,
         5,  87,   6,   7,   8,   9,  88,  89,  90,  10,  91,  92,  11,
        12,  93,  13,  89,  14,  94,  95,  15,  96,  97,  16,  98,  17,
        18,  19,  99, 100,  20,  21, 101,  98,  22, 102, 103, 104,  23,
       105,  24,  25,  26, 106,  17,  24,  27,  28,  29, 107, 108,  30,
       109,   8,  31, 110,  32,  33, 111,  99,  34,  35,  25, 112,  36,
       113,  35, 114,  37,  96, 115,  11, 116,  38, 117,  39, 118,  40,
       112,  41,  42,  43, 119, 110,  44,   4,  23, 105, 106,  45,  46,
       120,  47,  48,  18, 121,  10,  49,  50,  51, 122, 123,  52,  53,
       124, 125,  54, 126, 127, 128,  55,   6, 114, 129, 130,  56, 131,
       107,  57,  58,  58, 132,  59,  60, 133,  59, 134,  12,  39,  88,
        20,   1,   2,   5,  19, 128,  85,   9, 118, 135,  61,  62,  33,
       113,  63, 119,  63,  64,  65, 136,  56, 137,  31, 138, 139, 140,
        21,  66, 116, 141,  13, 129, 142, 139,  28, 143, 144,  16,  26,
        14, 126,  67,  34,  95, 145, 146,  93,  68,  84,  69,  55,  41,
       147,  87, 148, 149,  44, 111,  70,   3, 104, 150,  83, 146,  71,
        62, 140, 142,  72,  73, 141, 151, 134,  86,  52, 152,  74,  71,
       131,  75, 121,  15, 101, 127, 124, 153,  76, 154,  32, 145, 120,
        68,  46, 143,  27, 152,  42,  50,  91,  75, 144, 148, 155, 154,
       103,  80,  77,  49, 133, 137,  48, 151,  64, 156, 109,  69,  72,
        78, 135, 157,  73,  65,   7,  66, 156, 125, 158,  92, 130,  57,
       138,  67, 115,  45,  22, 150,  36,  29,  79, 132, 108, 157,  38,
        97,  82,  76,  37,  90, 149, 123,  47, 100, 155,  30,  74,  43,
        94,  70, 159,  81, 102,  79, 153, 122,  61, 159,  51,  60,  54,
        78, 147,  40, 136,  77, 158,  53, 117])

In [10]:
len(set(preds)) # смотрим, что все правильно

160

In [11]:
pd.DataFrame({'prediction': preds}).to_csv('best_submission.csv', index=False)